# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-25 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '帖子评论', 'verbose_name_plural': '帖子评论'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': '发布新帖', 'verbose_name_plural': '发布新帖'},
        ),
        migrations.AlterModelTable(
            name='comments',
            table='circle_comments',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='circle_questions',
        ),
    ]
