# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-24 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20191218_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='LikeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='项目名称')),
                ('link', models.URLField(default='', max_length=100, verbose_name='项目网址')),
                ('desc', models.CharField(max_length=200, verbose_name='项目介绍')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '项目交易',
                'verbose_name_plural': '项目交易',
                'db_table': 'trade_projects',
            },
        ),
        migrations.AddField(
            model_name='likeuser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Project'),
        ),
        migrations.AddField(
            model_name='likenum',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trade.Project'),
        ),
    ]
