# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-24 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20200224_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片路径'),
        ),
    ]
