# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('news_tip', models.CharField(max_length=100, verbose_name='文章摘要')),
                ('image_url', models.ImageField(upload_to='news/%Y/%m', verbose_name='图片路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
            ],
            options={
                'verbose_name': '新闻列表页',
                'verbose_name_plural': '新闻列表页',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('kind', models.SmallIntegerField(choices=[(1, 'APP'), (2, '桌面应用'), (3, '管理系统'), (4, '网站'), (5, 'UI设计'), (6, '小程序开发'), (7, '游戏开发'), (8, '其它分类')], default=8, verbose_name='项目类别')),
                ('budget', models.CharField(max_length=20, null=True, verbose_name='预算')),
                ('language', models.SmallIntegerField(choices=[(1, 'Python'), (2, 'Java'), (3, 'Android'), (4, 'C'), (5, 'PHP'), (6, 'GO'), (7, 'Perl'), (8, 'Lua'), (9, 'Other')], default=9, verbose_name='开发语言')),
                ('cycles', models.IntegerField(null=True, verbose_name='开发周期')),
                ('project_desc', models.TextField(default='项目描述', max_length=300, verbose_name='项目描述')),
                ('post_datetime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('views', models.IntegerField(default=0, verbose_name='浏览数量')),
                ('is_Active', models.BooleanField(default=True, verbose_name='项目状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'projects',
            },
        ),
    ]
