# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-25 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('outsource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(verbose_name='项目类别')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('post_datetime', models.DateTimeField(auto_now_add=True, verbose_name='发包时间')),
                ('end_datetime', models.DateTimeField(auto_now=True, verbose_name='截止时间')),
                ('skill', models.CharField(max_length=200, verbose_name='技能')),
                ('cycles', models.IntegerField(verbose_name='开发周期')),
                ('budget', models.CharField(max_length=20, verbose_name='预算')),
                ('compete_state', models.BooleanField(default=0, verbose_name='竞标状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '项目发布表',
                'verbose_name_plural': '项目发布表',
                'db_table': 'publish',
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
