# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0002_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_name', models.CharField(default='其它分类', max_length=30, verbose_name='项目类别')),
            ],
            options={
                'verbose_name': '项目类别选择表',
                'verbose_name_plural': '项目类别选择表',
                'db_table': 'kind_choice',
            },
        ),
        migrations.CreateModel(
            name='LanguageChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(default='暂无', max_length=30, verbose_name='开发语言')),
            ],
            options={
                'verbose_name': '开发语言选择表',
                'verbose_name_plural': '开发语言选择表',
                'db_table': 'language_choice',
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
