# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-21 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0002_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='projects_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.Projects'),
        ),
    ]
