# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-25 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0002_auto_20191125_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishproject',
            name='skill',
        ),
        migrations.AddField(
            model_name='publishproject',
            name='kind',
            field=models.CharField(choices=[('Android', 'Android'), ('Ios', 'Ios'), ('PC', 'PC网站'), ('wechart', '微信端开发'), ('other', '其它')], default='other', max_length=10, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='publishproject',
            name='project_descrption',
            field=models.TextField(default='项目描述', max_length=300, verbose_name='项目描述'),
        ),
    ]
