# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-10 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0003_auto_20191207_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='kind',
            field=models.CharField(default=8, max_length=100, verbose_name='项目类别'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(default=9, max_length=100, verbose_name='开发语言'),
        ),
    ]
