# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-25 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0003_auto_20191125_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishproject',
            name='kind',
            field=models.CharField(choices=[('Android', 'Android'), ('Ios', 'Ios'), ('PC', 'PC网站'), ('wechart', '微信端开发'), ('other', '其它')], default='other', max_length=50, verbose_name='类型'),
        ),
    ]
