# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191207_1159'),
        ('outsource', '0003_auto_20191207_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('kind', models.CharField(default=8, max_length=100, verbose_name='项目类别')),
                ('budget', models.CharField(blank=True, max_length=20, null=True, verbose_name='预算')),
                ('language', models.CharField(default=9, max_length=100, verbose_name='开发语言')),
                ('cycles', models.IntegerField(blank=True, null=True, verbose_name='开发周期')),
                ('project_desc', models.TextField(default='', max_length=300, verbose_name='项目描述')),
                ('post_datetime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '发布项目表',
                'verbose_name_plural': '发布项目表',
                'db_table': 'publish_project',
            },
        ),
    ]
