# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-01 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0004_jingbiao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jingbiao',
            old_name='project_id',
            new_name='project',
        ),
    ]
