# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-07 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0004_publishproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishproject',
            name='project_desc',
            field=models.TextField(default='项目描述', max_length=500, verbose_name='项目描述'),
        ),
    ]
