# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-11 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0004_auto_20191210_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=50, verbose_name='手机号')),
                ('price_min', models.CharField(max_length=50, verbose_name='最低价')),
                ('price_max', models.CharField(max_length=50, verbose_name='最高价')),
                ('work_status', models.CharField(max_length=50, verbose_name='工作状态')),
                ('work_direction', models.CharField(max_length=50, verbose_name='职业方向')),
                ('language_direction', models.CharField(max_length=50, verbose_name='语言方向')),
                ('sex', models.CharField(max_length=50, verbose_name='工作状态')),
                ('person_introduce', models.TextField(max_length=500, verbose_name='个人介绍')),
                ('work_experience', models.TextField(max_length=500, verbose_name='工作经历')),
                ('project_works', models.TextField(max_length=500, verbose_name='开发作品')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '开发者信息表',
                'verbose_name_plural': '开发者信息表',
                'db_table': 'developers',
            },
        ),
    ]
