# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-16 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0005_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_detail_url',
            field=models.URLField(default='#', verbose_name='详情页链接'),
        ),
    ]
