# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-02 13:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0005_auto_20200301_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '用户收藏项目表', 'verbose_name_plural': '用户收藏项目表'},
        ),
        migrations.AlterModelOptions(
            name='jingbiao',
            options={'verbose_name': '项目竞标表', 'verbose_name_plural': '项目竞标表'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterModelTable(
            name='collection',
            table='collection',
        ),
        migrations.AlterModelTable(
            name='jingbiao',
            table='jingbiao',
        ),
    ]
