# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0005_auto_20191125_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('news_tip', models.CharField(max_length=100, verbose_name='文章摘要')),
                ('image_url', models.ImageField(upload_to='news/%Y/%m', verbose_name='图片路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('index', models.IntegerField(default=999, verbose_name='排列顺序(从小到大)')),
            ],
            options={
                'verbose_name': '新闻列表页',
                'verbose_name_plural': '新闻列表页',
                'ordering': ['index', 'id'],
            },
        ),
    ]
