# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0006_news_news_detail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_tip',
            field=models.CharField(max_length=200, verbose_name='文章摘要'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=200, verbose_name='新闻标题'),
        ),
    ]
