# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200225_1909'),
        ('outsource', '0006_auto_20200302_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(default=0, verbose_name='竞标状态')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.Developers')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsource.Projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '确认开发者表',
                'verbose_name_plural': '确认开发者表',
                'db_table': 'confirm',
            },
        ),
    ]
