# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-16 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0007_auto_20191216_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻列表页', 'verbose_name_plural': '新闻列表页'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='index',
        ),
    ]
