# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-03 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0008_auto_20200303_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm',
            old_name='user',
            new_name='pub_user',
        ),
    ]
