# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-16 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0008_auto_20191216_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.ImageField(upload_to='', verbose_name='图片路径'),
        ),
    ]
