# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-03 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outsource', '0010_auto_20200303_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm',
            name='pub_user',
        ),
    ]
