# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200225_1909'),
        ('outsource', '0011_remove_confirm_pub_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
