# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-18 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
